server:
  port: 8084
spring:
  application:
    name: trade-service
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 172.29.199.37:8848
      config:
        import-check:
          enabled: false # 关闭配置文件的导入检查，当需要导入的配置文件不存在时，不会报错
        namespace: ${spring.profiles.active}
  config:
    import:
      - nacos:trade-service.yaml?group=TRADE_GROUP
      - nacos:common.yaml?group=DEFAULT_GROUP
      - nacos:shared-seata.yaml?group=DEFAULT_GROUP